### ISSUE TITLE
Documentation for Progress Info

### ISSUE THREAD

**Issue by nathanhaigh** [philres/ngmlr#24]
I'm using `ngmlr` for the first time....easy installation and easy to run. However, I don't know what all the information means in the reported progress info. Some documentation around this would be useful.

For example, my progress is currently showing:
```
Processed: 92198 (0.66), R/S: 37.44, RL: 8857, Time: 2.00 5.00 11.62, Align: 0.96, 490, 0.81
```

**Comment by nathanhaigh** [comment]
That's all good! The inclusion of this info in the readme would work be great!

**Comment by Nastiya** [comment]
Hi , Thanks for the explanation, but I got lost as well.
I run it for the first time, and as an output I've received two .ngm files.
How can I open these files, and where I can see the mapping of the mapped reads to my reference sequence.
Thanks

**Comment by fritzsedlazeck** [comment]
Hi Nastiya,
when you run ngm did you include reads? If you jus see the two .ngm files these are just the indexes from your reference. 
Please look at the readme with the information on how to run it. 
Thanks
Fritz

**Comment by Nastiya** [comment]
Dear @fritzsedlazeck ,
Thank you for the quick reply. I indeed received 3 files: 2 .ngm files and on .sam file.
Now, I'm trying to use Tablet to visualize it. I'm inserting .sam file as the assembly, but get an error of the reference file. Should I use one of these .ngm files as a reference instead of the original ref.fasta file I've used when running the ngmlr command?

Best.
A

**Comment by fritzsedlazeck** [comment]
Dear Nastiya,
please read the documentation of tablet. You certainly need to convert sam -> bam and sort it. (e.g. using samtools). You probably need further to index the reference file. 
This is unrelated to NGM so please contact them for support or read their documentaton. 
Thanks
Fritz
